<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>CWVehicles.ico</ApplicationIcon>
    <Copyright>SR File</Copyright>
    <Company>SR File</Company>
    <Product>SR File</Product>
    <Authors>SR File</Authors>
    <AssemblyName>SR File Vehicle Viewer</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeWalker\CodeWalker.csproj" />
  </ItemGroup>

</Project>